/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package IssuesForCh5

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun practiceClosure(): Pair<Int, () -> Int> {
    var localValue = 0
    val lamb = {localValue++}
    return Pair(localValue, lamb)
}

fun main(args: Array<String>) {
    var (localValue, lamb) = practiceClosure()
    println(Pair(practiceClosure().toList()[0], lamb()))
    println(Pair(practiceClosure().toList()[0], lamb()))
    println(Pair(practiceClosure().toList()[0], lamb()))
    println(Pair(practiceClosure().toList()[0], lamb()))
}
